name: Build
on: [push]
jobs:
  uberjar:
    name: Build uberjar release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: DeLaGuardo/setup-clojure@13.4
        with:
          cli: '1.11.4.1474'
      - name: Cache deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: deps-${{ hashFiles('deps.edn') }}
          restore-keys: deps-
      - name: Build
        run: clojure -T:build uber
      - name: Release name
        id: relname
        run: echo "relname=`cat resources/version`" >> $GITHUB_OUTPUT
      - name: Release
        uses: sotfprops/action-gh-release@v2.3.2
        with:
          files: target/pows-standalone.jar
          name: ${{ steps.relname.outputs.relname }}
          tag_name: ${{ steps.relname.outputs.relname }}
